version: "3.8"

services:

  postgresql:
    container_name: postgresql
    build:
      context: ./postgresql/
      args:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgresql
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  urlshortener:
    container_name: urlshortener
    depends_on:
      - postgresql
    build:
      context: ./urlShortener/
      args:
        SOLUTION: ${SOLUTION}
    image: urlshortener
    restart: always
    ports:
      - "8080:${URLSH_PORT}"

volumes:
  db-data:
    name: db-data