version: "3.8"

services:

  postgresql:
    container_name: postgresql
    build:
      context: ./postgresql/
      args:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgresql
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  urlshortener:
#    container_name: urlshortener
#    depends_on:
#      - postgresql
#    build: ./requirements/wordpress
#    image: wordpress
#    restart: always
#    environment:
#      - DB_HOST=${DB_HOST}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_NAME=${DB_NAME}
#    volumes:
#      - wordpress:/var/www/html/wordpress
#    networks:
#      - net

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/db-data
      o: bind
    name: db-data