bind_addr = ":8080"
log_level = "debug"
[options]
    schema = "http"
    prefix = "localhost:8080"
[storage]
    host = "localhost"
    port = "5432"
    database = "urlshort"
    username = "deedsbaron"
    password = "0809"
    attempts2con = 5