POST http://localhost:8080/encode/
Content-Type: application/json

{
  "longUrl":"https://vk.com/letsffucktheworld"
}
###
POST http://localhost:8080/encode/
Content-Type: application/json

{
  "longUrl":"https://www.postgresqltutorial.com/postgresql-where/"
}
###
POST http://localhost:8080/encode/
Content-Type: application/json

{
  "longUrl":"https://medium.com/geekculture/work-with-go-postgresql-using-pgx-caee4573672"
}
###
POST http://localhost:8080/encode/
Content-Type: application/json

{
  "longUrl":"https://www.google.com/search?q=how+to+form+correct+response+post+method&oq=how+to+form+correct+response+post+method&aqs=chrome..69i57.10120j0j4&sourceid=chrome&ie=UTF-8"
}
###

