GET http://localhost:8080/8l_iqDowO_o
Accept: application/json

###
POST http://localhost:8080/encode/
Content-Type: application/json

{
  "longUrl":"https://vk.com/letsffucktheworld"
}
###
POST http://localhost:8080/encode/
Content-Type: application/json

{
  "longUrl":"https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf"
}
###
POST http://localhost:8080/encode/
Content-Type: application/json

{
  "longUrl":"https://www.google.com/search?q=how+to+form+correct+response+post+method&oq=how+to+form+correct+response+post+method&aqs=chrome..69i57.10120j0j4&sourceid=chrome&ie=UTF-8"
}
###
POST http://localhost:8080/encode/
Content-Type: application/json

{
  "longUrl":"https://www.google.com/search?q=how+to+form+correct+response+post+method&oq=how+to+form+correct+response+post+method&aqs=chrome..69i57.10120j0j4&sourceid=chrome&ie=UTF-8"
}
###

